language: node_js

node_js:
  - "0.11"

before_install: npm install -g grunt-cli codeclimate-test-reporter

after_script:
  - mv coverage/*/lcov.info coverage/lcov.info
  - export CODECLIMATE_REPO_TOKEN=6ea18a5dd0ad06193948f3070fdc663ac49c61e597737bbdb2ac28a2b0c323be && codeclimate < coverage/lcov.info
