language: node_js

node_js:
- '0.10'

addons:
  sauce_connect: true

before_install: npm install -g grunt-cli codeclimate-test-reporter

after_script:
 - mv coverage/*/lcov.info coverage/lcov.info
 - export CODECLIMATE_REPO_TOKEN=27f8c2e8a2ceb8ff999d40efb9b9a68daf9c37a8c12d49e871b921f8ee9d8a3f
 - codeclimate < coverage/lcov.info
